### ISSUE TITLE
Update bot/guilds.json and add 2025/2026 server ID's

### ISSUE THREAD

**Issue by eesazahed** [VLCCommunity/VLCOneKey#3]
Otherwise a server admin will need to manually grant a user roles.

**Comment by yusufrahmn** [comment]
`guilds.json` is no longer in use, guild information is now stored in a MongoDB Collection.

**Comment by eesazahed** [comment]
Ok thanks anyway :)

**Comment by eesazahed** [comment]
Also one last thing (but i feel dumb for asking), I cloned the git repo to see if I could contribute to it, and i can't run it, even in dev mode. I looked over package.json. As a suggestion, I'd recommend creating a dev mongo database url, and you can keep the production mongo database url on replit.

**Comment by ghost** [comment]
Sorry we need to make a better readme.

To get started, copy the `.env.example` file as `.env` and fill in the appropriate environment variables.
Then, run `npm install` to install the required dependencies, and run the `dev` or `run` scripts.

We can't really make a public development database since it can be abused, but thank you for the suggestion!

**Comment by TheRedstoneRadiant** [comment]
One other thing to note, the `GOOGLE_SECRET` environment variable may not fully take effect as some static files like `views/index.ejs` have it embedded as a constant. This is something we need to fix.

**Comment by TheRedstoneRadiant** [comment]
Gonna creating new issues actully
